<html>
<head>
<title>Terms and Conditions</title>
</head>
<body>
<p>PRIVACY POLICY<br>
 <br>
Last revised: January 5th, 2014<br>
 <br>
INTRODUCTION<br>
Vibe LLC (&ldquo;Vibe&rdquo;, &ldquo;Us&rdquo;, &ldquo;Our&rdquo; or &ldquo;We&rdquo;) is concerned about privacy matters and wants you to be familiar with how We collect, use and disclose your personal information.<br>
 <br>
This Privacy Policy is incorporated into and forms part of the terms of service or use of any website or software application or service operated or provided by Vibe (collectively, &ldquo;Services&rdquo; and each is a &ldquo;Service&rdquo;).<br>
 <br>
By using a Service or otherwise providing Us with your personal information, you are accepting the practices described in this Privacy Policy, as they may be amended by Us from time to time, and agreeing to Our collection and use of your personal information in accordance with this Privacy Policy. The terms in this Privacy Policy may be changed so you should review it periodically for changes.<br>
 <br>
WHAT IS PERSONAL INFORMATION<br>
Personal information means any information about an identifiable individual given to Vibe by that individual. Personal information includes such things as age, telephone number, e-mail addresses and mailing address. Information about an individual collected from other Vibe users is not protected under this privacy agreement. <br>
WE ARE ACCOUNTABLE TO YOU<br>
Vibe is responsible for all personal information within its possession or control, including any personal information that is transferred to third parties for legal, regulatory, processing, storage or other purposes. We have employees who are accountable for compliance with these privacy and security principles. Our privacy officer is responsible for Our compliance and commitment to this Privacy Policy. We require a comparable level of protection from Our third party relations.<br>
WE LET YOU KNOW WHY WE COLLECT AND USE YOUR PERSONAL INFORMATION<br>
Vibe identifies the purpose for which your personal information is collected and will be used or disclosed. If that purpose is not listed below, We will do this before or at the time the information is actually being collected. All personal information collected by Us from Service visitors, registered users and other individuals (as applicable) is collected, at a minimum, for the following purposes:<br>
to administer and manage the Services and Our business operations;<br>
to identify or contact users of Services, respond to user inquiries and otherwise maintain relations with users;<br>
to provide users and prospective users with information about Our Services;<br>
to provide services requested by Our users;<br>
to bill, process and/or collect payment;<br>
to help prevent or investigate fraud, theft of power or other breaches of the law;<br>
to request user participation in surveys or contests;<br>
to comply with legal and governmental requirements;<br>
to perform statistical analyses of user behaviour and characteristics, in order to measure interest in and use of the various sections of a Service so as to improve design, navigation and experience of such Service; and/or<br>
fulfilling any other purpose that would be reasonably apparent to the average person at the time that We collect it.<br>
WE WILL OBTAIN YOUR CONSENT TO COLLECT, USE AND/OR DISCLOSE YOUR PERSONAL INFORMATION<br>
Vibe will obtain your consent before, or when, We collect, use and/or disclose your personal information. By accepting services from Us, using the Service, or otherwise providing Us with your personal information, you will be deemed to consent to Our use of your personal information for the purposes outlined above. Otherwise, Vibe will obtain your express consent (by verbal, written or electronic agreement) to collect, use or disclose your personal information. You can change your consent preferences at any time by contacting Vibe (please refer to the &ldquo;How to Contact Us&rdquo; section below).<br>
Vibe will not use or disclose your personal information for purposes other than those for which it was collected, except with your consent or as permitted or required by law or regulatory authorities. Your consent to the collection, use and/or disclosure of your personal information may be either express or implied, depending on the circumstances, the purposes for which such personal information is being collected and the sensitivity of the information.<br>
WE LIMIT COLLECTION OF YOUR PERSONAL INFORMATION<br>
Vibe collects only the information required to provide Our products and services to you. Vibe will collect personal information only by clear, fair and lawful means. We will not, as a condition of supplying you with a product or service, require you to consent to the collection, use or disclosure of information beyond that required to fulfill the specified, legitimate purpose.<br>
WHAT INFORMATION DO WE COLLECT?<br>
We may collect the following types of information from you:<br>
Registration Information: When You sign up for a user account for any of the Services, We will collect personal information, such as your name, email address and,other identifying information.<br>
IP Information: In general, We collect and use anonymous information and data regarding your access and use of Services and the Services. When you visit Services via a web browser, Our servers record the information that your browser automatically sends whenever visiting or using any of the Services, including Your web request, the Internet Protocol (&ldquo;IP&rdquo;) address and browser configuration of your Device (as defined below), the date and time of your request, the uniform resource locator of the referring and/or exiting websites. In this Privacy Policy, &ldquo;Device&rdquo; means a computer, mobile phone, handset, tablet or other device enabled for internet access and/or communication.<br>
Tags and Analytical Tracking: As part of making the Services available, We use tracking tools such as scripts, internet tags, cookies, graphic tags, web beacons and similar means (collectively, &ldquo;Tags&rdquo;) on the Services to enhance functionality and navigation for Our Service users. Portions of the Services may use analytical tools that are operated by Us and third party providers (collectively, the &ldquo;Analytical Tools&rdquo;).<br>
Vibe Feedback: Vibe collects information from its question and answer service. This information is collected anonymously.<br>
We may use Tags on the Services to count users and to recognize users by accessing Tags. Being able to access Tags allows Us to personalize the Services and improve your experience at the Services. We may also include Tags in HTML-formatted e-mail messages that We send to determine which e-mail messages were opened.<br>
Tags do not collect or contain your personal information. Information tracked through these mechanisms includes, but is not limited to: (i) your IP address and other IP information set out in (b) above; (ii) the type of web browser and operating system being used; (iii) the pages of Services that you visit; and/or (iv) other websites that you have viewed before visiting one of the Services. Some types of Tags, such as cookies, may be disabled whereas others may not. If you wish to disable cookies, refer to your browser help menu to learn how to disable cookies. Please note that if you disable cookies, you may be unable to access some customized features on the Services. Cookies do not collect or contain your personal information.<br>
In the case of Analytical Tools, the information generated by the Tags about your use of the Services (including your IP address) may be transmitted to and stored on servers located outside of Ontario including, but not limited to, other Canadian provinces and the United States. The information generated by the Tags may also be transferred to third party providers of Analytical Tools. This information will be used for the purpose of evaluating your use of the Services, compiling reports on Services activity and providing other services relating to Services activity and Internet usage. The third party providers of Analytical Tools may also transfer this information to other third parties where they are required to do so by law, or where such third parties process the information on their behalf.<br>
By using a Service, you consent to the processing of data about you by third party providers of Analytical Tools in the manner and for the purposes set out above.<br>
Information that You Provide: We may occasionally request from You or You may otherwise voluntarily provide Us with information that personally identifies You (including, but not limited to, product or service purchases, user support, contests, feedback, surveys and forums). We may receive personal information about You from a broad range of activities through the Services, including, but not limited to, Your inputs to the Services and general correspondence with Us. Depending on the service used, the personal information We collect may include contact information and demographic information.<br>
User communications: When You send email or other communications to Us, We may retain those communications in order to process Your inquiries, respond to Your requests and improve the Services and the Services.<br>
Under certain exceptional circumstances, Vibe may have a legal duty or right to collect, use or disclose your personal information without your knowledge or consent. In accordance with applicable laws, We will not disclose any consumer information (which may include personal information) without your written consent, except where consumer information is required to be disclosed: (i) for billing or market operation purposes; (ii) for law enforcement purposes; or (iii) for the purpose of complying with a legal requirement.<br>
We do not disclose personal information to any organization or person for any reason except as set out in this Privacy Policy and for the following purposes: (i) We may use service providers located outside of the United States, and, if applicable, your personal information may be processed and stored in other countries and therefore may be subject to disclosure under the laws of those jurisdictions; (ii) in the unlikely event of a proposed transfer of Vibe&rsquo;s business or assets (or a part thereof), or a merger or amalgamation of Vibe with another entity, We may disclose your personal information to third parties, such as prospective purchasers of Vibe&rsquo;s shares, business or assets, and to their lawyers, accountants, financial advisors, agents and other representatives as necessary for the purposes of such transaction and upon completion of such a transaction, your information will be one of the transferred assets; and/or (iii) where We otherwise have your express consent.<br>
You are deemed to consent to disclosure of your personal information for those purposes. If your personal information is shared by Us with third parties, those third parties are bound by appropriate agreements with Vibe to secure and protect the confidentiality of your personal information.<br>
Vibe will retain your personal information only for so long as is necessary to fulfill the purpose for which it was collected and to meet Our legal and contractual obligations. We will employ explicit retention periods for closed accounts, after which the personal information is destroyed or made anonymous.<br>
THE SECURITY OF YOUR PERSONAL INFORMATION IS A PRIORITY FOR Vibe<br>
We take steps to safeguard your personal information, regardless of the format in which it is held, including, but not limited to: (i) physical security measures, such as restricted access facilities and locked cabinets; (ii) electronic security measures for computerized personal information such as password protection, database encryption and personal identification numbers; (iii) organizational processes such as limiting access to your personal information to a selected group of individuals; and (iv) contractual obligations with third parties who need access to your personal information requiring them to protect and secure your personal information.<br>
WE ARE OPEN ABOUT OUR PRIVACY AND SECURITY POLICY<br>
We are committed to providing you with understandable and easily available information about Our policy and practices related to management of your personal information. This policy and any related information is available at all times on the Services or on request. To contact Us, refer to the &ldquo;How to Contact Us&rdquo; section below.<br>
WE PROVIDE ACCESS TO YOUR PERSONAL INFORMATION STORED BY US<br>
You can request access to your information stored by Us. Upon receiving such a request, Vibe will: (i) obtain satisfactory proof to confirm your identity; (ii) inform you about what type of information it has on record or in its control, how such information is used and to whom the information may have been disclosed; (iii) provide you with access to your information so you can review and verify the accuracy and completeness and request changes to the information; and (iv) make any necessary updates to your information. To access your personal information, refer to the &ldquo;How to Contact Us&rdquo; section below.<br>
WE RESPOND TO YOUR QUESTIONS, CONCERNS AND COMPLAINTS ABOUT PRIVACY<br>
Vibe responds in a timely manner to your questions, concerns and complaints about the privacy of your personal information and Our privacy policies and procedures.<br>
OTHER WEBSITES<br>
The Services have links to third party websites that Vibe does not own or maintain. Links to other websites or other resources which are not created or controlled by Vibe (&ldquo;Linked Sites&rdquo;) are intended for convenience only. Linked Sites are wholly independent from Vibe, therefore Vibe has no control over any products, services, materials, or other information contained in or available through these third party websites. We make no representations or warranties about the privacy practices of those websites. Therefore, access to any third party websites through Services, regardless of whether the third party website is a Linked Site or not, is entirely at your own risk and it is your responsibility to take all protective measures to guard against viruses or other destructive devices, programs.<br>
HOW TO CONTACT US<br>
You may contact Us by emailing Us at teamvibe@go-vibe.com If your questions, concerns and complaints have not been resolved to your satisfaction <br>
</p>
</body>
</html>